version: "3.7"

services:
  app: 
    build: 
      context: .
      dockerfile: Dockerfile
    command: sh -c "yarn install && yarn start"
    ports:
       - 3000:3000
    working_dir: /app
    volumes:
       - ./:/app